@startuml

left to right direction

class "User" as User {
}
class "Patient" as Patient1 {
    +patient-id-in-context
}
class "Patient" as Patient3 {
}
class "Encounter" as Encounter11 {
    +encounter-id-in-context
}
class "Encounter" as Encounter12 {
    +encounter-id-not-in-context
}
class "Patient" as Patient2 {
    +patient-id-not-in-context
}
class "Encounter" as Encounter21
class "Encounter" as Encounter22
class "Condition" as ConditionA
class "Condition" as ConditionB
class "Condition" as ConditionC
class "Condition" as ConditionD

User -- Patient1 : > "has access to"
User -- Patient2 : > "has access to"
User .. Patient3 : > "no access to"
Patient1 o-- Encounter11
Patient1 o-- Encounter12
Patient2 o-- Encounter21
Patient2 o-- Encounter22
Encounter11 o-- ConditionA
Encounter11 o-- ConditionB
Encounter12 o-- ConditionC
Encounter12 o-- ConditionD

@enduml